# 2.4 Propiedades y aplicaciones de matrices

Las matrices ocupan un lugar central en el álgebra lineal, no solo como objetos matemáticos, sino como herramientas fundamentales para resolver una gran variedad de problemas. Uno de sus usos más relevantes es en la resolución de sistemas de ecuaciones lineales, un problema clásico que surge en áreas tan diversas como la ingeniería, la economía, las ciencias computacionales y la física. Gracias a las matrices, podemos representar, manipular y resolver estos sistemas de manera ordenada y eficiente, especialmente cuando se trata de sistemas con muchas incógnitas.

Dentro de este contexto, el concepto de matriz inversa resulta particularmente importante. Así como los números reales tienen inversos multiplicativos (por ejemplo, el inverso de 2 es 1/2), algunas matrices también poseen inversas, y esto nos permite “deshacer” el efecto de una matriz, tal como hacemos al dividir por un número en una ecuación. La existencia de la matriz inversa es crucial, porque cuando una matriz asociada a un sistema de ecuaciones es invertible, podemos obtener la solución única del sistema de forma directa y elegante usando operaciones matriciales.

Sin embargo, no todas las matrices tienen inversa. Por ello, comprender las propiedades que determinan cuándo una matriz es invertible, así como las características y consecuencias de esta propiedad, resulta esencial. Las condiciones de invertibilidad están ligadas a conceptos como el determinante, el rango y la independencia lineal de los vectores columna o fila.

En este capítulo, exploraremos en detalle las propiedades de las matrices relacionadas con la existencia y el cálculo de la inversa, así como algunas aplicaciones clave. El objetivo es que puedas reconocer cuándo una matriz es invertible, entender las implicaciones de esta propiedad y aplicar estos conceptos a la resolución de sistemas de ecuaciones y otros problemas relevantes en álgebra lineal y sus aplicaciones.


## 2.4.1 Definición de inversa de una matriz


Sea $ A $ una matriz cuadrada de orden $ n $ (es decir, una matriz $ n \times n $) con entradas en el conjunto de los números reales (o en algún otro campo). Decimos que $ A $ es **invertible** (o no singular) si existe otra matriz $ B $ del mismo orden tal que se cumplen las siguientes condiciones:

$$
A B = B A = I_n
$$

donde $ I_n $ es la matriz identidad de orden $ n $. A la matriz $ B $ se le llama **inversa** de $ A $ y se denota por $ A^{-1} $. Es decir,

$$
A^{-1} A = A A^{-1} = I_n
$$

No todas las matrices cuadradas son invertibles. Una condición necesaria y suficiente para que $ A $ tenga inversa es que su determinante sea distinto de cero, es decir, $ \det(A) \neq 0 $.





### Cálculo de la inversa de una matriz

Una de las formas más directas y prácticas para calcular la inversa de una matriz cuadrada $ A $ es mediante el **método de reducción por filas** (también llamado método de Gauss-Jordan). Este método utiliza operaciones elementales sobre filas para transformar la matriz original en la matriz identidad, aplicando simultáneamente las mismas operaciones a la matriz identidad para obtener la inversa. Los pasos son los siguientes:

1. **Construye la matriz aumentada:**  
   Escribe la matriz $ A $ junto a la matriz identidad del mismo tamaño, formando la matriz aumentada $ [A \,|\, I] $.

2. **Aplica operaciones elementales por filas:**  
   Mediante operaciones elementales (intercambio de filas, multiplicación de una fila por un escalar distinto de cero, suma de múltiplos de una fila a otra), transforma la parte izquierda ($ A $) de la matriz aumentada en la matriz identidad $ I $.

3. **Obtén la inversa:**  
   Si logras transformar $ A $ en la identidad, la parte derecha de la matriz aumentada se habrá convertido en $ A^{-1} $. Es decir, $ [A \,|\, I] \longrightarrow [I \,|\, A^{-1}] $.

4. **Verifica:**  
   Si en algún paso no puedes continuar (por ejemplo, si encuentras un pivote cero que no puedes cambiar por otro no nulo), entonces $ A $ no es invertible.

Este método es especialmente útil para implementaciones computacionales y es la base de muchos algoritmos en álgebra lineal.


### Ejemplo: Cálculo de la inversa por reducción por filas

Supongamos la matriz  
$$
A = \begin{pmatrix}
2 & 1 \\
5 & 3 \\
\end{pmatrix}
$$

Vamos a calcular la inversa de $ A $ usando el método de reducción por filas (Gauss-Jordan):

Paso 1. Escribe la matriz aumentada $ [A \,|\, I] $

$$
\left(
\begin{array}{cc|cc}
2 & 1 & 1 & 0 \\
5 & 3 & 0 & 1 \\
\end{array}
\right)
$$


Paso 2. Haz que el elemento (1,1) sea 1 (divide la primera fila por 2)

$$
F_1 \leftarrow \frac{1}{2} F_1
$$

$$
\left(
\begin{array}{cc|cc}
1 & 0.5 & 0.5 & 0 \\
5 & 3 & 0 & 1 \\
\end{array}
\right)
$$


Paso 3. Haz que el elemento (2,1) sea 0  
Resta 5 veces la primera fila a la segunda fila:

$$
F_2 \leftarrow F_2 - 5 F_1
$$

$$
\left(
\begin{array}{cc|cc}
1 & 0.5 & 0.5 & 0 \\
0 & 0.5 & -2.5 & 1 \\
\end{array}
\right)
$$



Paso 4. Haz que el elemento (2,2) sea 1  
Divide la segunda fila entre 0.5:

$$
F_2 \leftarrow \frac{1}{0.5} F_2 = 2 F_2
$$

$$
\left(
\begin{array}{cc|cc}
1 & 0.5 & 0.5 & 0 \\
0 & 1 & -5 & 2 \\
\end{array}
\right)
$$



Paso 5. Haz que el elemento (1,2) sea 0  
Resta 0.5 veces la segunda fila a la primera fila:

$$
F_1 \leftarrow F_1 - 0.5 F_2
$$

$$
\left(
\begin{array}{cc|cc}
1 & 0 & 0.5 + 2.5 & 0 - 1 \\
0 & 1 & -5 & 2 \\
\end{array}
\right)
=
\left(
\begin{array}{cc|cc}
1 & 0 & 3 & -1 \\
0 & 1 & -5 & 2 \\
\end{array}
\right)
$$


Resultado

La parte derecha es la inversa de $ A $:
$$
A^{-1} = \begin{pmatrix}
3 & -1 \\
-5 & 2 \\
\end{pmatrix}
$$

Puedes comprobar que $ A A^{-1} = I $.

### Usando Python

In [2]:
import numpy as np

# Definir la matriz A
A = np.array([[2, 1],
              [5, 3]])

# Calcular la inversa de A
A_inv = np.linalg.inv(A)

print("Matriz original A:")
print(A)

print("\nInversa de A:")
print(A_inv)

# Comprobar que A * A_inv es la identidad
print("\nA * A_inv:")
print(np.dot(A, A_inv))



Matriz original A:
[[2 1]
 [5 3]]

Inversa de A:
[[ 3. -1.]
 [-5.  2.]]

A * A_inv:
[[ 1.00000000e+00  2.22044605e-16]
 [-8.88178420e-16  1.00000000e+00]]


## Propiedades de la inversa

Algunas propiedades importantes de la inversa de una matriz cuadrada $ A $ son:

- $ (A^{-1})^{-1} = A $
- $ (AB)^{-1} = B^{-1} A^{-1} $ si $ A $ y $ B $ son invertibles
- $ (A^T)^{-1} = (A^{-1})^T $
- Si $ c \neq 0 $ es un escalar, entonces $ (cA)^{-1} = \frac{1}{c} A^{-1} $
- La inversa de la matriz identidad es la propia identidad: $ (I)^{-1} = I $



## 2.4.2 Definición de transpuesta de una matriz y de la matriz adjunta $ Adj(A) $ como la transpuesta de la matriz de cofactores

## 2.4.3 Propiedades de la inversa

## 2.4.4 Definición de matriz identidad

## 2.4.5 Propiedades de la matriz identidad

## 2.4.6 Propiedades de la transpuesta de una matriz