# 2.4 Propiedades y aplicaciones de matrices

Las matrices ocupan un lugar central en el álgebra lineal, no solo como objetos matemáticos, sino como herramientas fundamentales para resolver una gran variedad de problemas. Uno de sus usos más relevantes es en la resolución de sistemas de ecuaciones lineales, un problema clásico que surge en áreas tan diversas como la ingeniería, la economía, las ciencias computacionales y la física. Gracias a las matrices, podemos representar, manipular y resolver estos sistemas de manera ordenada y eficiente, especialmente cuando se trata de sistemas con muchas incógnitas.

Dentro de este contexto, el concepto de matriz inversa resulta particularmente importante. Así como los números reales tienen inversos multiplicativos (por ejemplo, el inverso de 2 es 1/2), algunas matrices también poseen inversas, y esto nos permite “deshacer” el efecto de una matriz, tal como hacemos al dividir por un número en una ecuación. La existencia de la matriz inversa es crucial, porque cuando una matriz asociada a un sistema de ecuaciones es invertible, podemos obtener la solución única del sistema de forma directa y elegante usando operaciones matriciales.

Sin embargo, no todas las matrices tienen inversa. Por ello, comprender las propiedades que determinan cuándo una matriz es invertible, así como las características y consecuencias de esta propiedad, resulta esencial. Las condiciones de invertibilidad están ligadas a conceptos como el determinante, el rango y la independencia lineal de los vectores columna o fila.

En este capítulo, exploraremos en detalle las propiedades de las matrices relacionadas con la existencia y el cálculo de la inversa, así como algunas aplicaciones clave. El objetivo es que puedas reconocer cuándo una matriz es invertible, entender las implicaciones de esta propiedad y aplicar estos conceptos a la resolución de sistemas de ecuaciones y otros problemas relevantes en álgebra lineal y sus aplicaciones.


## 2.4.1 Matriz identidad

### Definición de la matriz identidad

Sea $ M $ un conjunto de Matrices de $ n \times n$ decimos que $ I $ es una matriz identidad en $ M $ si se cumple que $ A I = I A = A $ $ \forall A \in M $

Especificamente en el caso de las matrices de orden $ n $, tenemos que $ I_n $, es una matriz cuadrada de tamaño $ n \times n $ cuyos elementos de la diagonal principal son $ 1 $ y todos los demás elementos son $ 0 $:

$$
(I_n)_{ij} = \begin{cases}
1 & \text{si } i = j \\
0 & \text{si } i \neq j
\end{cases}
$$

### Ejemplo, la matriz identidad de orden 3 es:

$$
I_3 = \begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{pmatrix}

## 2.4.2 Definición de inversa de una matriz


Sea $ A $ una matriz cuadrada de orden $ n $ (es decir, una matriz $ n \times n $) con entradas en el conjunto de los números reales (o en algún otro campo). Decimos que $ A $ es **invertible** (o no singular) si existe otra matriz $ B $ del mismo orden tal que se cumplen las siguientes condiciones:

$$
A B = B A = I_n
$$

donde $ I_n $ es la matriz identidad de orden $ n $. A la matriz $ B $ se le llama **inversa** de $ A $ y se denota por $ A^{-1} $. Es decir,

$$
A^{-1} A = A A^{-1} = I_n
$$

No todas las matrices cuadradas son invertibles. Una condición necesaria y suficiente para que $ A $ tenga inversa es que su determinante sea distinto de cero, es decir, $ \det(A) \neq 0 $.



### Cálculo de la inversa de una matriz

Una de las formas más directas y prácticas para calcular la inversa de una matriz cuadrada $ A $ es mediante el **método de reducción por filas** (también llamado método de Gauss-Jordan). Este método utiliza operaciones elementales sobre filas para transformar la matriz original en la matriz identidad, aplicando simultáneamente las mismas operaciones a la matriz identidad para obtener la inversa. Los pasos son los siguientes:

1. **Construye la matriz aumentada:**  
   Escribe la matriz $ A $ junto a la matriz identidad del mismo tamaño, formando la matriz aumentada $ [A \,|\, I] $.

2. **Aplica operaciones elementales por filas:**  
   Mediante operaciones elementales (intercambio de filas, multiplicación de una fila por un escalar distinto de cero, suma de múltiplos de una fila a otra), transforma la parte izquierda ($ A $) de la matriz aumentada en la matriz identidad $ I $.

3. **Obtén la inversa:**  
   Si logras transformar $ A $ en la identidad, la parte derecha de la matriz aumentada se habrá convertido en $ A^{-1} $. Es decir, $ [A \,|\, I] \longrightarrow [I \,|\, A^{-1}] $.

4. **Verifica:**  
   Si en algún paso no puedes continuar (por ejemplo, si encuentras un pivote cero que no puedes cambiar por otro no nulo), entonces $ A $ no es invertible.

Este método es especialmente útil para implementaciones computacionales y es la base de muchos algoritmos en álgebra lineal.


### Ejemplo: Cálculo de la inversa por reducción por filas

Supongamos la matriz  
$$
A = \begin{pmatrix}
2 & 1 \\
5 & 3 \\
\end{pmatrix}
$$

Vamos a calcular la inversa de $ A $ usando el método de reducción por filas (Gauss-Jordan):

Paso 1. Escribe la matriz aumentada $ [A \,|\, I] $

$$
\left(
\begin{array}{cc|cc}
2 & 1 & 1 & 0 \\
5 & 3 & 0 & 1 \\
\end{array}
\right)
$$


Paso 2. Haz que el elemento (1,1) sea 1 (divide la primera fila por 2)

$$
F_1 \leftarrow \frac{1}{2} F_1
$$

$$
\left(
\begin{array}{cc|cc}
1 & 0.5 & 0.5 & 0 \\
5 & 3 & 0 & 1 \\
\end{array}
\right)
$$


Paso 3. Haz que el elemento (2,1) sea 0  
Resta 5 veces la primera fila a la segunda fila:

$$
F_2 \leftarrow F_2 - 5 F_1
$$

$$
\left(
\begin{array}{cc|cc}
1 & 0.5 & 0.5 & 0 \\
0 & 0.5 & -2.5 & 1 \\
\end{array}
\right)
$$



Paso 4. Haz que el elemento (2,2) sea 1  
Divide la segunda fila entre 0.5:

$$
F_2 \leftarrow \frac{1}{0.5} F_2 = 2 F_2
$$

$$
\left(
\begin{array}{cc|cc}
1 & 0.5 & 0.5 & 0 \\
0 & 1 & -5 & 2 \\
\end{array}
\right)
$$



Paso 5. Haz que el elemento (1,2) sea 0  
Resta 0.5 veces la segunda fila a la primera fila:

$$
F_1 \leftarrow F_1 - 0.5 F_2
$$

$$
\left(
\begin{array}{cc|cc}
1 & 0 & 0.5 + 2.5 & 0 - 1 \\
0 & 1 & -5 & 2 \\
\end{array}
\right)
=
\left(
\begin{array}{cc|cc}
1 & 0 & 3 & -1 \\
0 & 1 & -5 & 2 \\
\end{array}
\right)
$$


Resultado

La parte derecha es la inversa de $ A $:
$$
A^{-1} = \begin{pmatrix}
3 & -1 \\
-5 & 2 \\
\end{pmatrix}
$$

Puedes comprobar que $ A A^{-1} = I $.

### Usando Python

In [4]:
import numpy as np

# Definir la matriz A
A = np.array([[2, 1],
              [5, 3]])

# Calcular la inversa de A
A_inv = np.linalg.inv(A)

print("Matriz original A:")
print(A)

print("\nInversa de A:")
print(A_inv)

# Comprobar que A * A_inv es la identidad
print("\nA * A_inv:")
print(np.dot(A, A_inv))



Matriz original A:
[[2 1]
 [5 3]]

Inversa de A:
[[ 3. -1.]
 [-5.  2.]]

A * A_inv:
[[ 1.00000000e+00  2.22044605e-16]
 [-8.88178420e-16  1.00000000e+00]]


### Propiedades de la inversa

Algunas propiedades importantes de la inversa de una matriz cuadrada $ A $ son:

- $ (A^{-1})^{-1} = A $
- $ (AB)^{-1} = B^{-1} A^{-1} $ si $ A $ y $ B $ son invertibles
- $ (A^T)^{-1} = (A^{-1})^T $
- Si $ c \neq 0 $ es un escalar, entonces $ (cA)^{-1} = \frac{1}{c} A^{-1} $
- La inversa de la matriz identidad es la propia identidad: $ (I)^{-1} = I $



## 2.4.2 Matriz de cofactores

### Definición de matriz de cofactores

Sea $ A $ una matriz cuadrada de orden $ n $. La **matriz de cofactores** de $ A $ es la matriz del mismo tamaño que $ A $, donde cada elemento $ C_{ij} $ es el **cofactor** correspondiente al elemento $ A_{ij} $ de la matriz original.

El cofactor $ C_{ij} $ se define como:

$$
C_{ij} = (-1)^{i+j} M_{ij}
$$

donde $ M_{ij} $ es el **menor** de $ A $ asociado a la posición $ (i, j) $, es decir, el determinante de la submatriz que se obtiene al eliminar la fila $ i $ y la columna $ j $ de $ A $.

Por lo tanto, la **matriz de cofactores** es:

$$
\operatorname{Cof}(A) = \begin{pmatrix}
C_{11} & C_{12} & \cdots & C_{1n} \\
C_{21} & C_{22} & \cdots & C_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
C_{n1} & C_{n2} & \cdots & C_{nn}
\end{pmatrix}
$$

### Ejemplo: matriz de cofactores para una matriz $ 3 \times 3 $

Considera la matriz

$$
A = \begin{pmatrix}
1 & 2 & 3 \\
0 & 4 & 5 \\
1 & 0 & 6 \\
\end{pmatrix}
$$

Vamos a calcular el cofactor $ C_{ij} $ de cada elemento:



#### Cofactor $ C_{11} $

El menor $ M_{11} $ se obtiene eliminando la primera fila y la primera columna:

$$
M_{11} = \begin{vmatrix}
4 & 5 \\
0 & 6
\end{vmatrix} = (4)(6) - (0)(5) = 24
$$

$$
C_{11} = (+1) M_{11} = 24
$$



#### Cofactor $ C_{12} $

El menor $ M_{12} $ se obtiene eliminando la primera fila y la segunda columna:

$$
M_{12} = \begin{vmatrix}
0 & 5 \\
1 & 6
\end{vmatrix} = (0)(6) - (1)(5) = -5
$$

$$
C_{12} = (-1) M_{12} = -(-5) = 5
$$



#### Cofactor $ C_{13} $

El menor $ M_{13} $ se obtiene eliminando la primera fila y la tercera columna:

$$
M_{13} = \begin{vmatrix}
0 & 4 \\
1 & 0
\end{vmatrix} = (0)(0) - (1)(4) = -4
$$

$$
C_{13} = (+1) M_{13} = -4
$$



#### Cofactor $ C_{21} $

El menor $ M_{21} $ se obtiene eliminando la segunda fila y la primera columna:

$$
M_{21} = \begin{vmatrix}
2 & 3 \\
0 & 6
\end{vmatrix} = (2)(6) - (0)(3) = 12
$$

$$
C_{21} = (-1) M_{21} = -12
$$



#### Cofactor $ C_{22} $

El menor $ M_{22} $ se obtiene eliminando la segunda fila y la segunda columna:

$$
M_{22} = \begin{vmatrix}
1 & 3 \\
1 & 6
\end{vmatrix} = (1)(6) - (1)(3) = 3
$$

$$
C_{22} = (+1) M_{22} = 3
$$



#### Cofactor $ C_{23} $

El menor $ M_{23} $ se obtiene eliminando la segunda fila y la tercera columna:

$$
M_{23} = \begin{vmatrix}
1 & 2 \\
1 & 0
\end{vmatrix} = (1)(0) - (1)(2) = -2
$$

$$
C_{23} = (-1) M_{23} = 2
$$



#### Cofactor $ C_{31} $

El menor $ M_{31} $ se obtiene eliminando la tercera fila y la primera columna:

$$
M_{31} = \begin{vmatrix}
2 & 3 \\
4 & 5
\end{vmatrix} = (2)(5) - (4)(3) = 10 - 12 = -2
$$

$$
C_{31} = (+1) M_{31} = -2
$$



#### Cofactor $ C_{32} $

El menor $ M_{32} $ se obtiene eliminando la tercera fila y la segunda columna:

$$
M_{32} = \begin{vmatrix}
1 & 3 \\
0 & 5
\end{vmatrix} = (1)(5) - (0)(3) = 5
$$

$$
C_{32} = (-1) M_{32} = -5
$$



#### Cofactor $ C_{33} $

El menor $ M_{33} $ se obtiene eliminando la tercera fila y la tercera columna:

$$
M_{33} = \begin{vmatrix}
1 & 2 \\
0 & 4
\end{vmatrix} = (1)(4) - (0)(2) = 4
$$

$$
C_{33} = (+1) M_{33} = 4
$$



#### Matriz de cofactores

Por lo tanto, la matriz de cofactores de $ A $ es:

$$
\operatorname{Cof}(A) = \begin{pmatrix}
24 & 5 & -4 \\
-12 & 3 & 2 \\
-2 & -5 & 4 \\
\end{pmatrix}
$$


## 2.4.3 Matriz Adjunta $ Adj(A) $

### Definición de matriz adjunta $ Adj(A) $
La **matriz adjunta** o **adjunta** de una matriz cuadrada $ A $, denotada por $ Adj(A) $, es la **transpuesta de la matriz de cofactores de $ A $**. 

Así, la matriz de cofactores es la matriz donde cada entrada es el cofactor correspondiente:

$$
Adj(A) = \operatorname{Cof}(A)^T
$$

La adjunta se utiliza, por ejemplo, en la fórmula para calcular la inversa de una matriz:
$$
A^{-1} = \frac{1}{\det(A)} Adj(A)
$$
siempre que $ \det(A) \neq 0 $.


### Ejemplo: Cálculo de la matriz adjunta y la inversa usando la matriz de cofactores

Considera la matriz $ A $ del ejemplo anterior definida como:

$$
A = \begin{pmatrix}
1 & 2 & 3 \\
0 & 4 & 5 \\
1 & 0 & 6 \\
\end{pmatrix}
$$



#### 1. Calcula la matriz de cofactores

Ya calculamos anteriormente que la matriz de cofactores es:

$$
\operatorname{Cof}(A) = \begin{pmatrix}
24 & 5 & -4 \\
-12 & 3 & 2 \\
-2 & -5 & 4 \\
\end{pmatrix}
$$



#### 2. Calcula la matriz adjunta $ Adj(A) $

La **matriz adjunta** se obtiene como la transpuesta de la matriz de cofactores:

$$
Adj(A) = \operatorname{Cof}(A)^T
$$

Entonces,

$$
Adj(A) = \begin{pmatrix}
24 & -12 & -2 \\
5 & 3 & -5 \\
-4 & 2 & 4 \\
\end{pmatrix}
$$



#### 3. Calcula el determinante de $ A $

Ahora calculamos el determinante de $ A $ (puedes hacerlo usando cualquier método, aquí se expande por la primera fila):

$$
\det(A) = 1 \cdot
\begin{vmatrix}
4 & 5 \\
0 & 6
\end{vmatrix}
- 2 \cdot
\begin{vmatrix}
0 & 5 \\
1 & 6
\end{vmatrix}
+ 3 \cdot
\begin{vmatrix}
0 & 4 \\
1 & 0
\end{vmatrix}
$$

$$
= 1 \cdot (4 \cdot 6 - 0 \cdot 5) - 2 \cdot (0 \cdot 6 - 1 \cdot 5) + 3 \cdot (0 \cdot 0 - 1 \cdot 4)
$$

$$
= 1 \cdot 24 - 2 \cdot (-5) + 3 \cdot (-4)
= 24 + 10 - 12 = 22
$$



#### 4. Calcula la inversa de $ A $ usando la adjunta

La fórmula para la inversa de una matriz cuadrada $ A $ es:

$$
A^{-1} = \frac{1}{\det(A)} Adj(A)
$$

Por lo tanto,

$$
A^{-1} = \frac{1}{22} \begin{pmatrix}
24 & -12 & -2 \\
5 & 3 & -5 \\
-4 & 2 & 4 \\
\end{pmatrix}
$$

o, de forma explícita:

$$
A^{-1} = \begin{pmatrix}
\frac{24}{22} & \frac{-12}{22} & \frac{-2}{22} \\
\frac{5}{22} & \frac{3}{22} & \frac{-5}{22} \\
\frac{-4}{22} & \frac{2}{22} & \frac{4}{22} \\
\end{pmatrix}
$$



Así es como se obtiene la **matriz adjunta** y se utiliza para calcular la inversa de una matriz cuadrada.


## 2.4.4 Propiedades de la transpuesta de una matriz

### Propiedades de la transpuesta de una matriz

Sea $ A $ y $ B $ matrices de tamaños compatibles, y $ c $ un escalar. Las propiedades más importantes de la transpuesta son:

- **Doble transposición:**  
  $ (A^T)^T = A $

- **Transpuesta de una suma:**  
  $ (A + B)^T = A^T + B^T $

- **Transpuesta de un escalar por una matriz:**  
  $ (cA)^T = cA^T $

- **Transpuesta de un producto:**  
  $ (AB)^T = B^T A^T $

- **Transpuesta de la matriz identidad:**  
  $ (I_n)^T = I_n $

- **Transpuesta de una matriz inversa (si $ A $ es invertible):**  
  $ (A^{-1})^T = (A^T)^{-1} $

- **Transpuesta y determinante:**  
  $ \det(A^T) = \det(A) $

- **Transpuesta y matriz de cofactores:**  
  La transpuesta de la matriz de cofactores de $ A $ es la **adjunta** de $ A $:  
  $ Adj(A) = \operatorname{Cof}(A)^T $

  Además,  
  $ \operatorname{Cof}(A^T) = (\operatorname{Cof}(A))^T $


