# 1.1 Metodo De Gauss y Gauss-Jordan

Además de los métodos tradicionales para resolver sistemas de ecuaciones, como el método de sustitución o el método de suma y resta, y el metodo gráfico, existen otras formas más estructuradas y eficientes, especialmente útiles cuando se trata de sistemas con muchas incógnitas. Una de estas formas consiste en utilizar una **estructura matemática llamada matriz**.

En este contexto, **una matriz** es un arreglo rectangular de números dispuestos en filas y columnas. Las matrices nos permiten representar de manera compacta y ordenada la información de un sistema de ecuaciones lineales, lo que facilita la aplicación de métodos algorítmicos y el uso de herramientas computacionales.

Para asociar un sistema de ecuaciones lineales con una matriz, asignamos cada coeficiente de las incógnitas y cada término independiente a un lugar específico dentro de la matriz. Por ejemplo, consideremos el siguiente sistema:

$$
\begin{cases}
2x + 3y = 8 \\
x - 4y = -2
\end{cases}
$$

Podemos representar los coeficientes de las incógnitas en la **matriz de coeficientes**:

$$
A = \begin{bmatrix}
2 & 3 \\
1 & -4
\end{bmatrix}
$$

y los términos independientes en el **vector columna**:

$$
\mathbf{b} = \begin{bmatrix}
8 \\
-2
\end{bmatrix}
$$

Así, el sistema se puede expresar de manera abreviada como:

$$
A\mathbf{x} = \mathbf{b}
$$

donde 

$$
\mathbf{x} = \begin{bmatrix} x \\ y \end{bmatrix}
$$

es el vector de incógnitas. Esta notación matricial es fundamental en álgebra lineal y nos permitirá estudiar métodos más generales y potentes para resolver sistemas de ecuaciones.


## 1.1.1 Operaciones con matrices

Para comprender la notación matricial utilizada en la expresión $A\mathbf{x} = \mathbf{b}$, es importante familiarizarse con algunas operaciones básicas que se pueden realizar con matrices. Las matrices son estructuras fundamentales en el álgebra lineal y proporcionan un marco ordenado para organizar y manipular conjuntos de números.

Una **matriz** es un arreglo rectangular de números organizados en filas y columnas. Por ejemplo, una matriz de dos filas y tres columnas se puede escribir como:

$$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

Un **vector** es un caso especial de matriz que tiene solo una columna (vector columna) o una fila (vector fila). Por ejemplo, el siguiente es un vector columna de tres componentes:

$$
\mathbf{v} = \begin{bmatrix}
2 \\
-1 \\
4
\end{bmatrix}
$$

<hr style="height:2px; border:none; border-top:2px dashed #888888; margin:20px 0;">

### Notación de elementos de una matriz

Supongamos que $A$ es una matriz de $m$ filas y $n$ columnas:

$$
A = \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}
$$

- El **elemento $a_{ij}$** se refiere al elemento en la fila $i$ y la columna $j$ de la matriz $A$.
- El **renglón $i$** (también llamado **fila $i$**) es el conjunto de elementos $a_{i1}, a_{i2}, \ldots, a_{in}$.
- La **columna $j$** es el conjunto de elementos $a_{1j}, a_{2j}, \ldots, a_{mj}$.

**Ejemplo:**

Si

$$
A = \begin{bmatrix}
2 & 3 & 5 \\
4 & 1 & 0
\end{bmatrix}
$$

- El elemento $a_{21}$ es el que está en la fila 2, columna 1: $a_{21} = 4$.
- El renglón 1 es $[2, 3, 5]$.
- La columna 3 es $[5, 0]$.

<hr style="height:2px; border:none; border-top:2px dashed #888888; margin:20px 0;">


### Suma de matrices

Sean $A = [a_{ij}]$ y $B = [b_{ij}]$ dos matrices del mismo tamaño, es decir, ambas de orden $m \times n$ (con $m$ filas y $n$ columnas).

La **suma de matrices** $A + B$ se define como la matriz $C = [c_{ij}]$ también de orden $m \times n$, cuyos elementos se obtienen sumando los elementos correspondientes de $A$ y $B$:

$$
c_{ij} = a_{ij} + b_{ij} \qquad \text{para todo } 1 \leq i \leq m,\ 1 \leq j \leq n
$$

En otras palabras,

$$
A + B = [a_{ij}] + [b_{ij}] = [a_{ij} + b_{ij}]
$$

**Ejemplo:**

La **suma de matrices** se define solo para matrices del mismo tamaño. Para sumar dos matrices, se suman sus elementos correspondientes. Por ejemplo, si

$$
A = \begin{bmatrix}
1 & 3 \\
2 & 4
\end{bmatrix}, \quad
B = \begin{bmatrix}
5 & 0 \\
-1 & 2
\end{bmatrix}
$$

entonces

$$
A + B = \begin{bmatrix}
1 + 5 & 3 + 0 \\
2 + (-1) & 4 + 2
\end{bmatrix}
= \begin{bmatrix}
6 & 3 \\
1 & 6
\end{bmatrix}
$$

<hr style="height:2px; border:none; border-top:2px dashed #888888; margin:20px 0;">

### Producto de una matriz por un escalar

Sea $A = [a_{ij}]$ una matriz de tamaño $m \times n$, y sea $\lambda$ un número real (escalar).

El **producto de la matriz $A$ por el escalar $\lambda$** es la matriz $\lambda A = [\lambda a_{ij}]$ de tamaño $m \times n$, cuyos elementos se obtienen multiplicando cada elemento de $A$ por $\lambda$:

$$
(\lambda A)_{ij} = \lambda \cdot a_{ij}
$$

para todo $1 \leq i \leq m$, $1 \leq j \leq n$.


Es decir, el **producto de una matriz por un escalar** consiste en multiplicar cada elemento de la matriz por ese número. 

**Ejemplo:**

$$
C = \begin{bmatrix}
2 & -3 \\
0 & 5
\end{bmatrix}
$$

entonces

$$
3C = \begin{bmatrix}
3 \times 2 & 3 \times (-3) \\
3 \times 0 & 3 \times 5
\end{bmatrix}
= \begin{bmatrix}
6 & -9 \\
0 & 15
\end{bmatrix}
$$

<hr style="height:2px; border:none; border-top:2px dashed #888888; margin:20px 0;">

### Producto de matrices

Sean $A = [a_{ij}]$ una matriz de tamaño $m \times n$ y $B = [b_{jk}]$ una matriz de tamaño $n \times p$ (es decir, el número de columnas de $A$ coincide con el número de filas de $B$).

El **producto de matrices** $AB$ es una nueva matriz $C = [c_{ik}]$ de tamaño $m \times p$, cuyos elementos se definen así:

$$
c_{ik} = \sum_{j=1}^{n} a_{ij} b_{jk}
$$

para $1 \leq i \leq m$ y $1 \leq k \leq p$.

En otras palabras, el elemento en la fila $i$ y columna $k$ de $C$ se obtiene multiplicando los elementos de la fila $i$ de $A$ por los elementos de la columna $k$ de $B$, sumando los productos correspondientes.

**Ejemplo:**

$$
A = \begin{bmatrix}
1 & 0 & 2 \\
-1 & 3 & 1
\end{bmatrix}, \quad
B = \begin{bmatrix}
3 & 1 \\
2 & 1 \\
1 & 0
\end{bmatrix}
$$

entonces el producto $AB$ es una matriz $2 \times 2$:

$$
AB = \begin{bmatrix}
(1)(3) + (0)(2) + (2)(1) & (1)(1) + (0)(1) + (2)(0) \\
(-1)(3) + (3)(2) + (1)(1) & (-1)(1) + (3)(1) + (1)(0)
\end{bmatrix}
= \begin{bmatrix}
3 + 0 + 2 & 1 + 0 + 0 \\
-3 + 6 + 1 & -1 + 3 + 0
\end{bmatrix}
= \begin{bmatrix}
5 & 1 \\
4 & 2
\end{bmatrix}
$$



<hr style="height:2px; border:none; border-top:2px dashed #888888; margin:20px 0;">

### Matriz aumentada

La **matriz aumentada** de un sistema de ecuaciones lineales es una matriz que incluye, junto a los coeficientes de las incógnitas, una columna adicional con los términos independientes (las constantes del lado derecho de las ecuaciones).

Formalmente, si el sistema es:

$$
\begin{cases}
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n = b_1 \\
a_{21}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n = b_2 \\
\vdots \\
a_{m1}x_1 + a_{m2}x_2 + \cdots + a_{mn}x_n = b_m
\end{cases}
$$

La **matriz aumentada** es:

$$
\left[
\begin{array}{cccc|c}
a_{11} & a_{12} & \cdots & a_{1n} & b_1 \\
a_{21} & a_{22} & \cdots & a_{2n} & b_2 \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn} & b_m
\end{array}
\right]
$$


**Ejemplo:**

Considera el sistema:

$$
\begin{cases}
x + 2y = 5 \\
3x - y = 4
\end{cases}
$$

La matriz aumentada correspondiente es:

$$
\left[
\begin{array}{cc|c}
1 & 2 & 5 \\
3 & -1 & 4
\end{array}
\right]
$$



<hr style="height:2px; border:none; border-top:2px dashed #888888; margin:20px 0;">

### Operaciones elementales por renglón

Las **operaciones elementales por renglón** son transformaciones que se pueden aplicar a las filas de una matriz y que resultan fundamentales para resolver sistemas de ecuaciones y para llevar matrices a formas simplificadas, como la forma escalonada.

Existen tres tipos principales de operaciones elementales por renglón:

1. **Intercambio de renglones:**  
   Consiste en intercambiar el lugar de dos filas de la matriz.

   **Ejemplo:**  

   Si

   $$
   A = \begin{bmatrix}
   1 & 2 \\
   3 & 4
   \end{bmatrix}
   $$

   al intercambiar el renglón 1 y el renglón 2, obtenemos:

   $$
   \begin{bmatrix}
   3 & 4 \\
   1 & 2
   \end{bmatrix}
   $$

2. **Multiplicación de un renglón por un escalar no nulo:**  
   Consiste en multiplicar todos los elementos de una fila por un número distinto de cero.

   **Ejemplo:**  

   Si

   $$
   A = \begin{bmatrix}
   2 & -1 \\
   5 & 3
   \end{bmatrix}
   $$

   al multiplicar el renglón 1 por 3, obtenemos:
   
   $$
   \begin{bmatrix}
   6 & -3 \\
   5 & 3
   \end{bmatrix}
   $$

3. **Sumar a un renglón un múltiplo de otro renglón:**  
   Consiste en reemplazar una fila por la suma de esa fila y un múltiplo de otra fila.

   **Ejemplo:**  

   Si
   
   $$
   A = \begin{bmatrix}
   1 & 4 \\
   2 & 5
   \end{bmatrix}
   $$

   al sumar al renglón 2 el doble del renglón 1 (es decir, $R_2 \leftarrow R_2 + 2R_1$), obtenemos:
   
   
   $$
   \begin{bmatrix}
   1 & 4 \\
   2 + 2 \times 1 & 5 + 2 \times 4
   \end{bmatrix}
   =
   \begin{bmatrix}
   1 & 4 \\
   4 & 13
   \end{bmatrix}
   $$

## 1.1.2 Método de Gauss 

El **método de Gauss** es una técnica sistemática para resolver sistemas de ecuaciones lineales. Consiste en aplicar operaciones elementales por renglón para transformar la matriz aumentada del sistema en una **forma escalonada** (todos los elementos debajo de la diagonal principal son ceros). Una vez en esa forma, la solución del sistema puede encontrarse fácilmente mediante sustitución hacia atrás.

#### **Instrucciones del método de Gauss:**

1. **Escribe la matriz aumentada** del sistema.
2. **Utiliza operaciones elementales por renglón** (intercambio de filas, multiplicar una fila por un escalar no nulo, sumar a una fila un múltiplo de otra) para obtener ceros debajo de la diagonal principal, formando una matriz en **forma escalonada**.
3. **Realiza sustitución hacia atrás**: empieza desde la última ecuación y resuelve hacia arriba para encontrar los valores de las incógnitas.


### Ejemplo: Resolución de un sistema de ecuaciones por el método de Gauss

Resuelve el siguiente sistema utilizando el método de Gauss:

$$
\begin{cases}
x + 2y + 3z = 14 \\
2x + y + z = 10 \\
x + y + z = 9
\end{cases}
$$



#### **1. Escribe la matriz aumentada:**

$$
\left[
\begin{array}{ccc|c}
1 & 2 & 3 & 14 \\
2 & 1 & 1 & 10 \\
1 & 1 & 1 & 9
\end{array}
\right]
$$



#### **2. Haz ceros debajo del primer pivote (columna 1):**

- $R_2 \leftarrow R_2 - 2R_1$
- $R_3 \leftarrow R_3 - R_1$

$$
\begin{array}{cccc}
R_2: & 2-2(1) & 1-2(2) & 1-2(3) & 10-2(14) \\
& = 0 & -3 & -5 & -18 \\
R_3: & 1-1(1) & 1-1(2) & 1-1(3) & 9-1(14) \\
& = 0 & -1 & -2 & -5 \\
\end{array}
$$

La matriz ahora es:


#### **2. Haz cero debajo del segundo pivote (columna 2):**

$R_3 \leftarrow R_3 - \frac{1}{3}R_2$


La matriz es ahora:

$$
\left[
\begin{array}{ccc|c}
1 & 2 & 3 & 14 \\
0 & -3 & -5 & -18 \\
0 & 0 & -\frac{1}{3} & 1
\end{array}
\right]
$$



#### **3. Resuelve por sustitución hacia atrás:**

- De la última ecuación: $-\frac{1}{3}z = 1 \implies z = -3$
- Segunda ecuación: $-3y - 5z = -18$
  
  $-3y -5(-3) = -18 \implies -3y + 15 = -18 \implies -3y = -33 \implies y = 11$

- Primera ecuación: $x + 2y + 3z = 14$

  $x + 2(11) + 3(-3) = 14 \implies x + 22 - 9 = 14 \implies x + 13 = 14 \implies x = 1$



#### **5. Solución**

$$
x = 1, \quad y = 11, \quad z = -3
$$


## 1.1.3 Método de Gauss-Jordan

### Método de Gauss-Jordan

El **método de Gauss-Jordan** es una extensión del método de Gauss para resolver sistemas de ecuaciones lineales. Este método transforma la matriz aumentada del sistema en su **forma escalonada reducida por filas** (también llamada forma canónica o forma de identidad), donde la diagonal principal está compuesta por unos y todos los demás elementos en esas columnas son ceros. Así, la solución del sistema se lee directamente de la matriz resultante, sin necesidad de sustitución hacia atrás.



#### **Instrucciones del método de Gauss-Jordan:**


1. **Empieza como en el método de Gauss**: escribe la matriz aumentada y haz ceros debajo de la diagonal principal.
2. **Continúa** aplicando operaciones elementales para hacer ceros también **arriba de la diagonal principal**, y asegura que la diagonal tenga unos.
3. **Lee la solución directamente** de la matriz resultante.



### **Ejemplo:** Resolver el sistema

$$
\begin{cases}
x + 2y + 3z = 14 \\
2x + y + z = 10 \\
x + y + z = 9
\end{cases}
$$



#### **1. Matriz aumentada**

$$
\left[
\begin{array}{ccc|c}
1 & 2 & 3 & 14 \\
2 & 1 & 1 & 10 \\
1 & 1 & 1 & 9
\end{array}
\right]
$$



#### **1. Transformación a forma escalonada reducida**

**Paso 1:** Restamos 2 veces la fila 1 a la fila 2 y la fila 1 a la fila 3:

- $R_2 \leftarrow R_2 - 2R_1$
- $R_3 \leftarrow R_3 - R_1$


Hacemos que el pivote de la fila 2 sea 1:

- $R_2 \leftarrow -\frac{1}{3}R_2$

$$
\left[
\begin{array}{ccc|c}
1 & 2 & 3 & 14 \\
0 & 1 & \frac{5}{3} & 6 \\
0 & -1 & -2 & -5
\end{array}
\right]
$$



Eliminamos el término en la posición (3,2):

- $R_3 \leftarrow R_3 + R_2$

$$
\left[
\begin{array}{ccc|c}
1 & 2 & 3 & 14 \\
0 & 1 & \frac{5}{3} & 6 \\
0 & 0 & -\frac{1}{3} & 1
\end{array}
\right]
$$



Hacemos que el pivote de la fila 3 sea 1:

- $R_3 \leftarrow -3R_3$

$$
\left[
\begin{array}{ccc|c}
1 & 2 & 3 & 14 \\
0 & 1 & \frac{5}{3} & 6 \\
0 & 0 & 1 & -3
\end{array}
\right]
$$



**Paso 2** Eliminamos los términos arriba del pivote en la columna 3:

- $R_2 \leftarrow R_2 - \frac{5}{3}R_3$
- $R_1 \leftarrow R_1 - 3R_3$

Calculando:

- $R_2$: $6 - \frac{5}{3} \cdot (-3) = 6 + 5 = 11$, y el coeficiente en $z$ será $0$.
- $R_1$: $14 - 3 \cdot (-3) = 14 + 9 = 23$, el coeficiente en $z$ será $0$.

La matriz ahora:

$$
\left[
\begin{array}{ccc|c}
1 & 2 & 0 & 23 \\
0 & 1 & 0 & 11 \\
0 & 0 & 1 & -3
\end{array}
\right]
$$



Eliminamos el término arriba del pivote en la columna 2 en la fila 1:

- $R_1 \leftarrow R_1 - 2R_2$

$23 - 2 \cdot 11 = 23 - 22 = 1$, y el coeficiente en $y$ será $0$.

$$
\left[
\begin{array}{ccc|c}
1 & 0 & 0 & 1 \\
0 & 1 & 0 & 11 \\
0 & 0 & 1 & -3
\end{array}
\right]
$$



#### **3. Solución directa**

$$
x = 1, \quad y = 11, \quad z = -3
$$



**Con Gauss-Jordan, la solución se lee directamente de la matriz final sin sustitución.**


## 1.1.4 Matrices elementales



En la sección anterior vimos que las **operaciones elementales por renglón** permiten transformar matrices hasta obtener formas más simples (como la forma escalonada).  

De manera análoga, podemos representar estas operaciones mediante **matrices elementales**.  
Cada operación elemental tiene asociada una matriz elemental, y al multiplicar una matriz $A$ por esa matriz elemental obtenemos el mismo resultado que aplicar la operación elemental a $A$.



### Ejemplo inicial

Sea la matriz

$$
A = \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}
$$

Trata de adivinar la forma que deben tener las siguientes matrices elementales $E$ para que:

1. $EA$ multiplique solo el **primer renglón** de $A$ por $3$.  
2. $EA$ **intercambie dos renglones** de $A$.  
3. $EA$ reemplace el **segundo renglón** por $R_2 + R_1$ (es decir, sume al segundo renglón lo que tiene el primero).  



**Resolviendo en Python**


In [1]:
import numpy as np

# Matriz original
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print("Matriz A original:\n", A)

# 1. Multiplicar el primer renglón por 3
E1 = np.array([[3,0,0],
               [0,1,0],
               [0,0,1]])
print("\nE1*A (primer renglón x3):\n", E1 @ A)

# 2. Intercambiar el primer y segundo renglón
E2 = np.array([[0,1,0],
               [1,0,0],
               [0,0,1]])
print("\nE2*A (intercambio de renglones 1 y 2):\n", E2 @ A)

# 3. Reemplazar el segundo renglón por R2 + R1
E3 = np.array([[1,0,0],
               [1,1,0],
               [0,0,1]])
print("\nE3*A (R2 -> R2 + R1):\n", E3 @ A)


Matriz A original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

E1*A (primer renglón x3):
 [[3 6 9]
 [4 5 6]
 [7 8 9]]

E2*A (intercambio de renglones 1 y 2):
 [[4 5 6]
 [1 2 3]
 [7 8 9]]

E3*A (R2 -> R2 + R1):
 [[1 2 3]
 [5 7 9]
 [7 8 9]]



### Forma general de las matrices elementales

De los ejemplos anteriores, podemos extraer las **formas generales** de cada tipo de matriz elemental en $\mathbb{R}^n$:

- **Multiplicar un renglón $i$ por un escalar $k \neq 0$:**
  
  $$E = I \quad \text{pero con } E_{ii} = k$$

- **Intercambiar los renglones $i$ y $j$:**
  
  $$E = I \quad \text{pero con las filas $i$ y $j$ intercambiadas}$$

- **Reemplazar el renglón $i$ por $R_i + kR_j$:**
  
  $$E = I \quad \text{pero con } E_{ij} = k$$



Las matrices elementales desempeñan un papel fundamental en el álgebra lineal porque permiten representar las operaciones elementales únicamente mediante multiplicaciones de matrices. Esto resulta especialmente importante en la práctica, dado que los GPUs son procesadores diseñados y altamente optimizados para realizar multiplicaciones matriciales de manera masiva y eficiente. Gracias a ello, algoritmos centrales como la eliminación gaussiana pueden implementarse de forma computacionalmente más rápida utilizando estas representaciones. Además, el concepto de matrices elementales constituye la base para el desarrollo de un algoritmo de cálculo de la inversa de una matriz, ya que esta puede obtenerse aplicando sucesivamente operaciones elementales representadas por dichas matrices.


### Ejemplo de calculo de inversa de una matriz por el método de la matriz aumentada $ [A \mid I] $


Sea

$$
A =
\begin{pmatrix}
1 & 1 & 1 \\
1 & 2 & 3 \\
0 & 1 & 1
\end{pmatrix}
$$


Partimos de la matriz aumentada $[A \mid I]$:

$$
\left[
\begin{array}{ccc|ccc}
1 & 1 & 1 & 1 & 0 & 0 \\
1 & 2 & 3 & 0 & 1 & 0 \\
0 & 1 & 1 & 0 & 0 & 1
\end{array}
\right]
$$



**Paso 1. Anular la entrada debajo del pivote de la primera columna**

Operación: $ R_2 \leftarrow R_2 - R_1 $

$$
\left[
\begin{array}{ccc|ccc}
1 & 1 & 1 & 1 & 0 & 0 \\
0 & 1 & 2 & -1 & 1 & 0 \\
0 & 1 & 1 & 0 & 0 & 1
\end{array}
\right]
$$



**Paso 2. Anular la entrada en la tercera fila, segunda columna**

Operación: $ R_3 \leftarrow R_3 - R_2 $

$$
\left[
\begin{array}{ccc|ccc}
1 & 1 & 1 & 1 & 0 & 0 \\
0 & 1 & 2 & -1 & 1 & 0 \\
0 & 0 & -1 & 1 & -1 & 1
\end{array}
\right].
$$



**Paso 3. Anular la entrada en la primera fila, segunda columna**

Operación: $ R_1 \leftarrow R_1 - R_2 $

$$
\left[
\begin{array}{ccc|ccc}
1 & 0 & -1 & 2 & -1 & 0 \\
0 & 1 & 2 & -1 & 1 & 0 \\
0 & 0 & -1 & 1 & -1 & 1
\end{array}
\right]
$$



**Paso 4. Normalizar el pivote de la tercera columna**

Operación: $ R_3 \leftarrow -\,R_3 $

$$
\left[
\begin{array}{ccc|ccc}
1 & 0 & -1 & 2 & -1 & 0 \\
0 & 1 & 2 & -1 & 1 & 0 \\
0 & 0 & 1 & -1 & 1 & -1
\end{array}
\right]
$$



**Paso 5. Hacer ceros arriba del pivote de la tercera columna**

Operaciones:
- $ R_2 \leftarrow R_2 - 2R_3 $
- $ R_1 \leftarrow R_1 + R_3 $

$$
\left[
\begin{array}{ccc|ccc}
1 & 0 & 0 & 1 & 0 & -1 \\
0 & 1 & 0 & 1 & -1 & 2 \\
0 & 0 & 1 & -1 & 1 & -1
\end{array}
\right].
$$



**Conclusión**
La parte izquierda quedó como la identidad; por tanto, la parte derecha es $ A^{-1} $:


$$
A^{-1} =
\begin{pmatrix}
1 & 0 & -1 \\
1 & -1 & 2 \\
-1 & 1 & -1
\end{pmatrix}.
$$

Verificación conceptual: se cumple $ A\,A^{-1} = I $ y $ A^{-1}A = I $.



**Verificación en Python (opcional)**



In [2]:
import numpy as np

A = np.array([[1,1,1],
              [1,2,3],
              [0,1,1]], dtype=int)

A_inv = np.array([[ 1,  0, -1],
                  [ 1, -1,  2],
                  [-1,  1, -1]], dtype=int)

print("A @ A_inv =\n", A @ A_inv)
print("A_inv @ A =\n", A_inv @ A)


A @ A_inv =
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
A_inv @ A =
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


###  Demostración formal

Sea $ A \in \mathbb{R}^{n \times n} $. Se forma la matriz aumentada $ [A \mid I] $.  
Si mediante **operaciones elementales por renglón** se transforma la parte izquierda en la identidad:

$$
[A \mid I] \;\;\underset{\text{operaciones elementales}}{\longrightarrow}\;\; [\, I \mid B \,],
$$

entonces **$ A $ es invertible** y **$ B = A^{-1} $**.  
Si no es posible llevar la parte izquierda a $ I $, entonces $ A $ **no** es invertible.

A continuación se demuestra paso a paso utilizando la correspondencia entre **operaciones elementales** y **matrices elementales**.


**Paso 1. Cada operación elemental por renglón es multiplicación por una matriz elemental**

Llamaremos **matriz elemental** a la matriz que se obtiene de la identidad $ I $ aplicando **una sola** operación elemental por renglón. Existen tres tipos:

1. **Escalamiento de renglón**: $ R_i \leftarrow k\,R_i $ con $ k \neq 0 $.  
   La matriz elemental es $ E = I $ salvo que en la entrada $ (i,i) $ se coloca $ k $.  
   Para cualquier matriz $ M $, se cumple $ EM $ = “$ M $ con el renglón $ i $ multiplicado por $ k $”.

2. **Intercambio de renglones**: $ R_i \leftrightarrow R_j $.  
   La matriz elemental es $ E = I $ con las **filas** $ i $ y $ j $ permutadas.  
   Para cualquier $ M $, se cumple $ EM $ = “$ M $ con los renglones $ i $ y $ j $ permutados”.

3. **Suma de múltiplo de otro renglón**: $ R_i \leftarrow R_i + k\,R_j $.  
   La matriz elemental es $ E = I $ salvo que en la **posición** $ (i,j) $ se pone $ k $.  
   Para cualquier $ M $, se cumple $ EM $ = “$ M $ con el renglón $ i $ reemplazado por $ R_i + k\,R_j $”.

**Justificación**: si denotamos por $ e_1,\dots,e_n $ a los vectores de la base canónica, la **fila** $ i $ de $ EM $ es precisamente la combinación lineal de filas de $ M $ definida por la **fila** $ i $ de $ E $. Como en cada caso la fila de $ E $ codifica exactamente la operación elemental, se obtiene la igualdad deseada.



**Paso 2. Encadenar operaciones elementales equivale a multiplicar por el producto de matrices elementales**

Supongamos que desde $ A $ aplicamos una sucesión de $ k $ operaciones elementales por renglón, con matrices elementales asociadas $ E_1, E_2, \dots, E_k $. Entonces:

$$
E_k \cdots E_2 E_1 \, A \;=\; A^{(k)},
$$

donde $ A^{(k)} $ es el resultado final tras esas operaciones.  
En particular, si hemos reducido por renglones hasta la identidad, obtenemos:

$$
E_k \cdots E_2 E_1 \, A \;=\; I.
$$

Denotemos:

$$
E \;=\; E_k \cdots E_2 E_1.
$$

Como cada $ E_i $ es invertible, su producto $ E $ también lo es. La igualdad anterior se reescribe como:

$$
E\,A \;=\; I.
$$


**Paso 3. Identificación de la inversa de $ A $**

De $ E\,A = I $ se concluye (por unicidad de la inversa a izquierda de una matriz cuadrada) que **$ E = A^{-1} $**.  

Es decir:

$$
A^{-1} \;=\; E_k \cdots E_2 E_1.
$$


**Paso 4. ¿Por qué aparece $ A^{-1} $ en el lado derecho de la aumentada?**

Si partimos de la aumentada $ [A \mid I] $ y aplicamos **las mismas** operaciones elementales por renglón a **ambos bloques**, el efecto es multiplicar a izquierda por las mismas matrices elementales:

$$
[A \mid I] \;\;\underset{E_1}{\longrightarrow}\;\; [\, E_1 A \mid E_1 I \,]
\;\;\underset{E_2}{\longrightarrow}\;\; [\, E_2 E_1 A \mid E_2 E_1 I \,]
\;\;\cdots\;\;\underset{E_k}{\longrightarrow}\;\; [\, E A \mid E I \,].
$$

Si la parte izquierda llega a ser la identidad, tenemos:

$$
[\, I \mid E \,].
$$

Pero por el Paso 3, $ E = A^{-1} $. Por lo tanto, el **bloque derecho** al finalizar el proceso es precisamente **$ A^{-1} $**.



**Paso 5. ¿Y si no puedo llegar a $ I $?**

Si al reducir por renglones la parte izquierda de $ [A \mid I] $ aparece una fila nula antes de lograr pivotes en todas las columnas, entonces **$ \operatorname{rango}(A) < n $**.  
En tal caso, **no** existe sucesión de matrices elementales que satisfaga $ E A = I $ y, por tanto, **$ A $ no es invertible**.



**Paso 6. Unicidad del resultado (independencia del camino)**

Puede haber muchas secuencias distintas de operaciones elementales que lleven $ A $ a $ I $.  
Si se llega a $ I $, el producto total $ E $ cumple siempre $ E A = I $.  
Por unicidad de la inversa, todas las secuencias producen el **mismo** $ E = A^{-1} $.  
De aquí que el método sea **bien definido**: el bloque derecho final no depende del camino de reducción.


**Conclusión**

- Cada operación elemental por renglón es una multiplicación a izquierda por una matriz elemental invertible.  
- Si una sucesión de tales operaciones transforma $ A $ en $ I $, entonces el producto de las matrices elementales asociadas es $ A^{-1} $.  
- Aplicar esa misma sucesión al bloque identidad en $ [A \mid I] $ devuelve precisamente ese producto en el bloque derecho, es decir, $ A^{-1} $.  
- Si no se puede alcanzar $ I $, entonces $ A $ no es invertible.

Por ello, el procedimiento de **Gauss–Jordan sobre la aumentada** $ [A \mid I] $ es correcto y completo: finaliza en $ [\, I \mid A^{-1} \,] $ si y solo si $ A $ es invertible.
